package install

import (
	"fmt"
	"strings"
	"time"

	"github.com/Sebas1705/WinForge/internal/catalog"
)

// Script renders a plan as a PowerShell script a person can read, review and
// run on any PC that has winget - no WinForge needed. Recipes are included as
// data (single-quoted here-strings), each run in its own powershell so an
// "exit" inside one cannot end the script.
func Script(cat *catalog.Catalog, plan Plan, title string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n# Generated by WinForge on %s. Review before running.\n", title, time.Now().Format("2006-01-02"))
	b.WriteString("# Each step continues if the previous one fails; read the output.\n\n")
	if plan.NeedsAdmin {
		b.WriteString("# Some steps need an elevated PowerShell (Run as administrator).\n\n")
	}
	b.WriteString(`function Invoke-Recipe([string]$Name, [string]$Check, [string]$Body) {
    Write-Host "== $Name"
    $env:Path = [Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [Environment]::GetEnvironmentVariable('Path','User')
    if ($Check) {
        powershell -NoProfile -ExecutionPolicy Bypass -Command $Check
        if ($LASTEXITCODE -eq 0) { Write-Host 'already satisfied'; return }
    }
    powershell -NoProfile -ExecutionPolicy Bypass -Command $Body
}

`)
	for _, s := range plan.Steps {
		switch s.Kind {
		case StepApp:
			fmt.Fprintf(&b, "Write-Host '== %s'\nwinget %s\n\n", psEscape(s.Name), joinArgs(WingetArgs(cat.Apps[s.ID], s.Version)))
		case StepUpgrade:
			fmt.Fprintf(&b, "Write-Host '== Update %s'\nwinget %s\n\n", psEscape(s.Name), joinArgs(WingetUpgradeArgs(cat.Apps[s.ID])))
		case StepUninstall:
			fmt.Fprintf(&b, "Write-Host '== Remove %s'\nwinget %s\n\n", psEscape(s.Name), joinArgs(WingetUninstallArgs(cat.Apps[s.ID])))
		case StepRecipe:
			r := cat.Recipes[s.ID]
			fmt.Fprintf(&b, "Invoke-Recipe '%s' @'\n%s\n'@ @'\n%s\n'@\n\n", psEscape(r.Description), strings.TrimSpace(r.Check), strings.TrimSpace(r.PowerShell))
		}
	}
	return b.String()
}

func psEscape(s string) string { return strings.ReplaceAll(s, "'", "''") }

func joinArgs(args []string) string {
	out := make([]string, len(args))
	for i, a := range args {
		if strings.ContainsAny(a, " \t\"'$`&;|<>()") {
			out[i] = "'" + psEscape(a) + "'"
		} else {
			out[i] = a
		}
	}
	return strings.Join(out, " ")
}
