// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1) {
  return window['go']['main']['App']['Apply'](arg1);
}

export function ApplyUpgrades(arg1) {
  return window['go']['main']['App']['ApplyUpgrades'](arg1);
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExportProfile(arg1) {
  return window['go']['main']['App']['ExportProfile'](arg1);
}

export function ExportScript(arg1) {
  return window['go']['main']['App']['ExportScript'](arg1);
}

export function ExportWinget(arg1) {
  return window['go']['main']['App']['ExportWinget'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Plan(arg1) {
  return window['go']['main']['App']['Plan'](arg1);
}

export function PlanUpgrades(arg1) {
  return window['go']['main']['App']['PlanUpgrades'](arg1);
}

export function ProfileFromPC(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProfileFromPC'](arg1, arg2, arg3);
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function Upgrades() {
  return window['go']['main']['App']['Upgrades']();
}
