// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1) {
  return window['go']['main']['App']['Apply'](arg1);
}

export function ApplyUninstall(arg1) {
  return window['go']['main']['App']['ApplyUninstall'](arg1);
}

export function ApplyUpgrades(arg1) {
  return window['go']['main']['App']['ApplyUpgrades'](arg1);
}

export function BackupSets() {
  return window['go']['main']['App']['BackupSets']();
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DiscardPending() {
  return window['go']['main']['App']['DiscardPending']();
}

export function ExportProfile(arg1) {
  return window['go']['main']['App']['ExportProfile'](arg1);
}

export function ExportScript(arg1) {
  return window['go']['main']['App']['ExportScript'](arg1);
}

export function ExportWinget(arg1) {
  return window['go']['main']['App']['ExportWinget'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function HealthScan() {
  return window['go']['main']['App']['HealthScan']();
}

export function HealthUpdates() {
  return window['go']['main']['App']['HealthUpdates']();
}

export function ImportCode(arg1) {
  return window['go']['main']['App']['ImportCode'](arg1);
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function InstallWinget() {
  return window['go']['main']['App']['InstallWinget']();
}

export function OpenLink(arg1) {
  return window['go']['main']['App']['OpenLink'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickBackup() {
  return window['go']['main']['App']['PickBackup']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function Plan(arg1) {
  return window['go']['main']['App']['Plan'](arg1);
}

export function PlanPending() {
  return window['go']['main']['App']['PlanPending']();
}

export function PlanUninstall(arg1) {
  return window['go']['main']['App']['PlanUninstall'](arg1);
}

export function PlanUpgrades(arg1) {
  return window['go']['main']['App']['PlanUpgrades'](arg1);
}

export function ProfileFromPC(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProfileFromPC'](arg1, arg2, arg3);
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function RestoreFolders(arg1, arg2) {
  return window['go']['main']['App']['RestoreFolders'](arg1, arg2);
}

export function RestoreSettings(arg1) {
  return window['go']['main']['App']['RestoreSettings'](arg1);
}

export function ResumePending() {
  return window['go']['main']['App']['ResumePending']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function ShareCode(arg1) {
  return window['go']['main']['App']['ShareCode'](arg1);
}

export function Upgrades() {
  return window['go']['main']['App']['Upgrades']();
}
