// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catalog} from '../models';
import {settings} from '../models';
import {main} from '../models';
import {install} from '../models';

export function Apply(arg1:catalog.Profile):Promise<void>;

export function ApplyUninstall(arg1:Array<string>):Promise<void>;

export function ApplyUpgrades(arg1:Array<string>):Promise<void>;

export function BackupSets():Promise<Array<settings.Found>>;

export function Cancel():Promise<void>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function CreateBackup(arg1:main.BackupRequest):Promise<main.BackupResult>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DiscardPending():Promise<void>;

export function Emulation():Promise<catalog.Emulation>;

export function ExportProfile(arg1:catalog.Profile):Promise<string>;

export function ExportScript(arg1:catalog.Profile):Promise<string>;

export function ExportWinget(arg1:catalog.Profile):Promise<string>;

export function GamesState():Promise<main.GamesView>;

export function GetState():Promise<main.State>;

export function HealthScan():Promise<main.HealthResult>;

export function HealthUpdates():Promise<main.HealthResult>;

export function ImportCode(arg1:string):Promise<main.ImportResult>;

export function ImportProfile():Promise<main.ImportResult>;

export function InstallGame(arg1:string):Promise<main.GameInstalled>;

export function InstallUpdate():Promise<void>;

export function InstallWinget():Promise<void>;

export function OpenGameFolder(arg1:string):Promise<void>;

export function OpenLink(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PatchROM():Promise<main.PatchResult>;

export function PickBackup():Promise<main.BackupPreview>;

export function PickFolder():Promise<string>;

export function Plan(arg1:catalog.Profile):Promise<install.Plan>;

export function PlanPending():Promise<install.Plan>;

export function PlanUninstall(arg1:Array<string>):Promise<install.Plan>;

export function PlanUpgrades(arg1:Array<string>):Promise<install.Plan>;

export function PlayGame(arg1:string,arg2:string):Promise<void>;

export function ProfileFromPC(arg1:string,arg2:string,arg3:boolean):Promise<catalog.Profile>;

export function RemoveGame(arg1:string):Promise<void>;

export function RestartAsAdmin():Promise<void>;

export function RestoreFolders(arg1:Array<string>,arg2:string):Promise<settings.FolderResult>;

export function RestoreSettings(arg1:Array<string>):Promise<settings.Result>;

export function ResumePending():Promise<void>;

export function SaveProfile(arg1:catalog.Profile):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;

export function SetGamesRoot():Promise<string>;

export function ShareCode(arg1:catalog.Profile):Promise<string>;

export function Upgrades():Promise<Array<main.UpgradeInfo>>;
