// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catalog} from '../models';
import {main} from '../models';
import {install} from '../models';

export function Apply(arg1:catalog.Profile):Promise<void>;

export function Cancel():Promise<void>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportProfile(arg1:catalog.Profile):Promise<string>;

export function ExportWinget(arg1:catalog.Profile):Promise<string>;

export function GetState():Promise<main.State>;

export function ImportProfile():Promise<main.ImportResult>;

export function InstallUpdate():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Plan(arg1:catalog.Profile):Promise<install.Plan>;

export function ProfileFromPC(arg1:string,arg2:string,arg3:boolean):Promise<catalog.Profile>;

export function RestartAsAdmin():Promise<void>;

export function SaveProfile(arg1:catalog.Profile):Promise<void>;
